name: Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.6
        uses: actions/setup-python@v5
        with:
          python-version: '3.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run --source=sysconfig_inspector -m unittest discover tests

      - name: Generate detailed coverage report (for debugging)
        run: |
          coverage report -m > coverage_details.txt 
          coverage html -d coverage_html_report    
      
      - name: Upload coverage artifacts (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-debug-report
          path: |
            coverage_details.txt
            coverage_html_report/ 

      - name: Check 100% coverage
        run: |
          coverage report --fail-under=100
